Controllers/CourseManageController.cs
using identity_2auth_mvc.Data;
using identity_2auth_mvc.Models;
using identity_2auth_mvc.Models.Klas;
using identity_2auth_mvc.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using identity_2auth_mvc.Enums;
using Microsoft.AspNetCore.Mvc.Rendering;
using identity_2auth_mvc.Utilities;

namespace identity_2auth_mvc.Controllers
{
	public class CourseManageController : Controller
	{
		private readonly ApplicationDbContext _db;
		private readonly UserManager<AppUser> _userManager;
		
		[BindProperty(SupportsGet = true)]
		public CourseViewModel CourseVM { get; set; }

		public CourseManageController(ApplicationDbContext db, UserManager<AppUser> userManager)
		{
			_db = db;
			_userManager = userManager;
		}

		public async Task<IActionResult> Index()
		{
			var courses = await _db.Course.ToListAsync();
			return View(courses);
		}


		public async Task<IActionResult> Detail(int? id)
		{
			if (id == null)
				return NotFound();

			var course = await _db.Course.Where(c => c.CourseID == id).FirstOrDefaultAsync();
			if (course == null)
				return NotFound();

			return View(course);
		}


		// AppUsers are Student and Lecturer
		[HttpGet]
		public async Task<IActionResult> Upsert(int? id)
		{
			List<SelectListItem> professorsList = new List<SelectListItem>();
			List<SelectListItem> teachingAssList = new List<SelectListItem>();
			CourseVM.AppUsers = _db.AppUsers.ToList();
			foreach (var lecturer in CourseVM.AppUsers)
			{
				if (await _userManager.IsInRoleAsync(lecturer, Enums.Roles.Professor.ToString()))
				{
					professorsList.Add(
						new SelectListItem { Text = lecturer.UserName, Value = lecturer.Id.ToString() }
						);
				}
				else if (await _userManager.IsInRoleAsync(lecturer, Enums.Roles.TA.ToString()))
				{
					teachingAssList.Add(
						new SelectListItem { Text = lecturer.UserName, Value = lecturer.Id.ToString() }
					);
				}
			}

			/*	ViewBag.ProfessorDropdownList = professorsList;
				ViewBag.TeachingAssistantDropdownList = teachingAssList;
	*/
			CourseVM = new CourseViewModel()
			{
				Course = new Course(),
				Enrollments = new List<Enrollment>(),
				CourseAssignment = new CourseAssignment(),
				ProfessorList = professorsList,
				TAList = teachingAssList,
				CourseTypeList = GetCourseTypeDropdownList()
			};

			if (id != null)
			{
				CourseVM.Course = await _db.Course.Where(c => c.CourseID == id)
					.Include(c => c.CourseSchedule).Where(c => c.CourseID == id)
					.Include(ce => ce.CourseAssignments)
						.ThenInclude(l => l.Lecturer)
					.Include(e => e.Enrollments)
						.ThenInclude(s => s.Student)
					.AsNoTracking()
					.FirstOrDefaultAsync();
			}

			return View(CourseVM);
		}


	/*	private async void PopulateLecturerList()
		{
		
			List<SelectListItem> professorsList = new List<SelectListItem>();
			List<SelectListItem> teachingAssList = new List<SelectListItem>();
			CourseVM.AppUsers = _db.AppUsers.ToList();
			foreach (var lecturer in CourseVM.AppUsers)
			{
				if (await _userManager.IsInRoleAsync(lecturer, Enums.Roles.Professor.ToString()))
				{
					professorsList.Add(
						new SelectListItem { Text = lecturer.UserName, Value = lecturer.Id.ToString() }
						);
				}
				else if(await _userManager.IsInRoleAsync(lecturer, Enums.Roles.TA.ToString()))
				{
					teachingAssList.Add(
						new SelectListItem { Text = lecturer.UserName, Value = lecturer.Id.ToString() }
					);
				}
			}

			*//*ViewBag.ProfessorDropdownList = professorsList;
			ViewBag.TeachingAssistantDropdownList = teachingAssList;*//*
		}*/

	
	

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Upsert()
		{
			if (ModelState.IsValid)
			{
				if (CourseVM.Course.CourseID == 0)
				{
				/*	CourseVM.Course = new Course()
					{
						CourseID = CourseVM.Course.CourseID,
						CourseCredit = CourseVM.Course.CourseCredit,
						CourseName = CourseVM.Course.CourseName,
						CourseType = CourseVM.Course.CourseType,
						CourseDescription = CourseVM.Course.CourseDescription,
						CourseSchedule = new CourseSchedule()
						{
							ClassPlace1 = CourseVM.Course.CourseSchedule.ClassPlace1,
							ClassTime1 = CourseVM.Course.CourseSchedule.ClassTime1,
							ClassPlace2 = CourseVM.Course.CourseSchedule.ClassPlace2,
							ClassTime2 = CourseVM.Course.CourseSchedule.ClassTime2
						}
					};
*//*
					if (CourseVM.Course == null)
						return NotFound();*/

					try
					{
						await _db.Course.AddAsync(CourseVM.Course);
						await _db.CourseAssignments.AddAsync(CourseVM.CourseAssignment);
						_db.SaveChanges();
					}
					catch (Exception ex)
					{
						ModelState.AddModelError("Unable to save changes. " +
								"Try again, and if the problem persists, " +
								"see your system administrator.", ex.Message);
					}
				}
				else
				{
					var courseModel = await _db.Course.Where(c => c.CourseID == CourseVM.Course.CourseID)
						.FirstOrDefaultAsync();
					var courseAssignment = await _db.CourseAssignments.Where(c => c.CourseID == CourseVM.Course.CourseID)
						.FirstOrDefaultAsync();

					if (courseModel == null)
						return NotFound();

					if (await TryUpdateModelAsync<Course>(courseModel,"",
						c => c.CourseName,
						c => c.CourseType,
						c => c.CourseCredit,
						c => c.CourseDescription,
						c => c.CourseSchedule.ClassTime1,
						c => c.CourseSchedule.ClassPlace2,
						c => c.CourseSchedule.ClassTime2,
						c => c.CourseSchedule.ClassPlace2
					) && (await TryUpdateModelAsync<CourseAssignment>(courseAssignment, "",
						cs => cs.Course.CourseName,
						cs => cs.Lecturer.UserName)))
					{
						try
						{
							_db.Course.Update(CourseVM.Course);
							_db.CourseAssignments.Update(CourseVM.CourseAssignment);
							await _db.SaveChangesAsync();
							return RedirectToAction(nameof(Index));
						}
						catch (DbUpdateException)
						{
							ModelState.AddModelError("", "Unable to save changes. " +
							"Try again, and if the problem persists, " +
							"see your system administrator.");
						}
					}
				}

				// await _db.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			else
			{
				Console.WriteLine($"{CourseVM.Course}");
			}

			return View(CourseVM);
		}

		/*	[HttpPost]
			[ValidateAntiForgeryToken]
			public async Task<IActionResult> Upsert(int? id)
			{
				var viewModel = new CourseViewModel();
				if (ModelState.IsValid)
				{
					// create newly
					if (viewModel.Course.CourseID != 0)
					{


					}
					else
					{
						// update
						viewModel.Course = await _db.Course.Where(c => c.CourseID == id)
							.Include(c => c.CourseSchedule).Where(c => c.CourseID == id)
							.Include(ce => ce.CourseAssignments)
								.ThenInclude(l => l.Lecturer)
							.Include(e => e.Enrollments)
								.ThenInclude(s => s.Student)
							.AsNoTracking()
							.FirstOrDefaultAsync();

						if (viewModel.Course == null)
							return NotFound();

						if (await TryUpdateModelAsync<Course>(viewModel.Course,"",
							c => c.CourseName,
							c => c.CourseType,
							c => c.CourseCredit,
							c => c.CourseDescription,
							c => c.CourseSchedule.ClassTime1,
							c => c.CourseSchedule.ClassPlace2,
							c => c.CourseSchedule.ClassTime2,
							c => c.CourseSchedule.ClassPlace2
						))
						{
							try
							{
								await _db.SaveChangesAsync();
							}
							catch (DbUpdateException)
							{
								ModelState.AddModelError("", "Unable to save changes. " +
								"Try again, and if the problem persists, " +
								"see your system administrator.");
							}
						}
					}

						return RedirectToAction(nameof(Index));
				}

				return View(viewModel.Course);
			}*/

		private void PopulateCourseTypeList()
		{
			List<SelectListItem> courseTypeList = new List<SelectListItem>();
			foreach (var courseType in StaticDetails.CourseTypes)
			{
				courseTypeList.Add(new SelectListItem
				{
					Text = courseType,
					Value = StaticDetails.CourseTypes.IndexOf(courseType).ToString()
				});
			}

			ViewBag.CourseTypeDropdownList = courseTypeList;
		}


		private void GetCourseAssignmentDropdownList(int? courseID)
		{
			var courseAssigments = _db.CourseAssignments.Where(c => c.CourseID == courseID)
									.AsNoTracking()
									.Include(l => l.Lecturer).ToList();
			ViewBag.CourseID = new SelectList(courseAssigments, "CourseID", "CourseName", courseID);
		}


		private void GetCourseAssignments(int courseId)
		{
			var getCoursesByLecturerId = _db.CourseAssignments
						.Include(l => l.Lecturer)
						.FirstOrDefault(c => c.CourseID == courseId);

		}

		private IList<SelectListItem> GetCourseTypeDropdownList()
		{

			List<SelectListItem> courseTypeListItem = new List<SelectListItem>();
			foreach (var courseType in StaticDetails.CourseTypes)
			{
				courseTypeListItem.Add(new SelectListItem { Text = courseType, Value = StaticDetails.CourseTypes.IndexOf(courseType).ToString() });
			}

			return courseTypeListItem;
		}


		#region APIs CALL
		[HttpGet]
		public IActionResult GetAll()
		{
			var objDetails = _db.Course.ToList();
			return Json(new { data = objDetails });
		}

		[HttpDelete]
		public IActionResult Delete(int id)
		{
			var objToDelete = _db.Course.Find(id);
			if (objToDelete == null)
				return Json(new { success = false, messge = "Error while deleting." });

			_db.Course.Remove(objToDelete);
			_db.SaveChanges();
			return Json(new { success = true, mesage = "Deleted successfully." });
		}

		#endregion 


	}
}

Controllers/RolesManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using identity_2auth_mvc.Enums;

namespace identity_2auth_mvc.Controllers
{
	[Authorize(Roles = "SuperAdmin")]
	public class RolesManagerController: Controller
	{
		private readonly RoleManager<IdentityRole> _roleManager;
		public RolesManagerController(RoleManager<IdentityRole> roleManager) 
		{
			_roleManager = roleManager;
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			var roles = await _roleManager.Roles.ToListAsync();
			return View(roles);
		}

		[HttpPost]
		public async Task<IActionResult> AddRole(string roleName)
		{
			if (roleName != string.Empty)
			{
				var role = await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
			}

			return RedirectToAction("Index");
		} 
	} 
} 

Controllers/UserRolesController.cs
using identity_2auth_mvc.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace identity_2auth_mvc.Controllers
{ 
	[Authorize(Roles = "SuperAdmin")]
	public class UserRolesController: Controller
	{
		private readonly UserManager<AppUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;

		public UserRolesController(UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager)
		{
			_userManager = userManager;
			_roleManager = roleManager;
		}

		public async Task<List<string>> GetUserRoles(AppUser user)
		{
			return new List<string>(await _userManager.GetRolesAsync(user));
		} 

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			var users = await _userManager.Users.ToListAsync();
			var userViewModel = new List<UserRoleViewModel>();
			foreach (AppUser user in users)
			{
				var currentViewModel = new UserRoleViewModel();
				currentViewModel.UserId = user.Id;
				currentViewModel.UserName = user.UserName;
				currentViewModel.Roles = await GetUserRoles(user);
				userViewModel.Add(currentViewModel);
			}

			return View(userViewModel);
		}

		[Authorize(Roles = "SuperAdmin")]
		[HttpGet]
		public async Task<IActionResult> Manage(string userId)
		{
			ViewBag.userId = userId;
			var user = await _userManager.FindByIdAsync(userId);
			if (user == null)
			{
				ViewBag.ErrorMessage = $"User with Id = {userId} could not found.";
				return NotFound();
			}
			ViewBag.UserName = user.UserName;
			var model = new List<ManageUsersRoleViewModel>();
			foreach (var role in _roleManager.Roles.ToList())
			{
				var userRolesViewModel = new ManageUsersRoleViewModel
				{
					RoleId = role.Id,
					RoleName = role.Name
				};
				if (await _userManager.IsInRoleAsync(user, role.Name))
				{
					userRolesViewModel.IsSelectedRole = true;
				}
				else
				{
					userRolesViewModel.IsSelectedRole = false;
				}

				model.Add(userRolesViewModel);
			}

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Manage(List<ManageUsersRoleViewModel> model, string userId)
		{
			var user = await _userManager.FindByIdAsync(userId);
			if (user == null)
			{
				return View();
			}
			var roles = await _userManager.GetRolesAsync(user);
			var result = await _userManager.RemoveFromRolesAsync(user, roles);
			if (!result.Succeeded)
			{
				ModelState.AddModelError("", "Cannot remove user existing roles");
				return View(model);
			}
			result = await _userManager.AddToRolesAsync(user, model.Where(x => x.IsSelectedRole).Select(y => y.RoleName));
			if (!result.Succeeded)
			{
				ModelState.AddModelError("", "Cannot add selected roles to user");
				return View(model);
			}
			return RedirectToAction("Index");
		}
	}
}

Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
	<div class="col">
		<button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Update</button>
	</div>
	<div class="col">
		<a asp-action="Index" class="btn btn-success form-control">Back To List</a>
	</div>
</div>

Views/Shared/_Layout.cshtml
@using System.Security.Claims 
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - identity_2auth_mvc</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />

	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">identity_2auth_mvc</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<partial name="_LoginPartial" />
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<div class="dropdown">
								<a class="nav-link text-dark dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="cursor:pointer;">
									System Manager
								</a>
								<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
									<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
									<a class="nav-link text-dark" asp-area="" asp-controller="RolesManager" asp-action="Index">Role Manager</a>
									<a class="nav-link text-dark" asp-area="" asp-controller="UserRoles" asp-action="Index">User Roles</a>
								</div>
							</div>
						</li>
						<li class="nav-item">
							<div class="dropdown">
								<a class="nav-link text-dark dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="cursor:pointer;">
									KLAS Services
								</a>
								<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
									<a class="nav-link text-dark" asp-area="" asp-controller="CourseManage" asp-action="Index">Course Manage</a>
									<a class="nav-link text-dark" asp-area="" asp-controller="RolesManager" asp-action="Index">Role Manager</a>
									<a class="nav-link text-dark" asp-area="" asp-controller="UserRoles" asp-action="Index">User Roles</a>
								</div>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>



	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2021 - identity_2auth_mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
	<script src="https://kit.fontawesome.com/e19c476714.js"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>