Models/Klas/NoticeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace identity_2auth_mvc.Models.Klas
{
	public class NoticeViewModel: NoticeModel
	{
		public Byte[] Data { get; set; }
		public int CourseId { get; set; }
		public virtual Course Course { get; set; }
	}
}

Controllers/NoteController.cs
using identity_2auth_mvc.Data;
using identity_2auth_mvc.Models.Klas;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace identity_2auth_mvc.Controllers
{
	public class NoteController : Controller
	{
		private readonly ApplicationDbContext _context;

		public NoteController(ApplicationDbContext context)
		{
			_context = context;
		}

		public async Task<IActionResult> Index()
		{
			List<SelectListItem> listItem = new List<SelectListItem>();
			var courses = await _context.Course.ToListAsync();
			foreach (var course in courses)
			{
				listItem.Add(new SelectListItem { Text = course.CourseName, Value = course.CourseID.ToString() });
			}

			ViewBag.CourseList = listItem;
			return View();
		}

		[HttpGet]
		public async Task<IActionResult> GetNoteById(int id)
		{
			var noteModel = await _context.Course
					.Include(n => n.Notices)
						.AsNoTracking()
						.FirstOrDefaultAsync(m => m.CourseID == id);

			if (noteModel == null)
				return Json(new { data = NotFound(), message = "Error while retrieving data." });

			return Json(noteModel);
		}

	
		public async Task<IActionResult> Detail(int? id)
		{	
			var notice = await _context.Notice.Where(x => x.Id == id).FirstOrDefaultAsync();
			if (notice == null) return NotFound();
			return View(notice);
		}


		[HttpPost]
		public async Task<IActionResult> UploadNoteToDB(List<IFormFile> files, string description, int courseId)
		{
			foreach (var file in files)
			{
				var fileName = Path.GetFileNameWithoutExtension(file.FileName);
				var extension = Path.GetExtension(file.FileName);
				var noticeModel = new NoticeViewModel
				{
					CourseId = courseId,
					CreatedOn = DateTime.Now,
					FileType = file.ContentType,
					Extension = extension,
					Name = fileName,
					Description = description
				};

				using (var dataStream = new MemoryStream())
				{
					await file.CopyToAsync(dataStream);
					noticeModel.Data = dataStream.ToArray();
				}

				_context.Notice.Add(noticeModel);
				await _context.SaveChangesAsync();
			}

			TempData["Message"] = "File successfully updated to Database.";
			return RedirectToAction("Index");
		}

		// download file that attached in notice 
		public async Task<IActionResult> DownloadNoteFromDB(int id)
		{
			var file = await _context.Notice.Where(x => x.Id == id).FirstOrDefaultAsync();
			if (file == null) return null;
			return File(file.Data, file.FileType, file.Name + file.Extension);
		}

		public async Task<IActionResult> DeleteNoteFromDB(int id)
		{
			var file = await _context.Notice.Where(x => x.Id == id).FirstOrDefaultAsync();
			if (file == null) return null;
			_context.Notice.Remove(file);
			await _context.SaveChangesAsync();
			TempData["Message"] = $"Removed {file.Name + file.Extension} successfully from database.";
			return RedirectToAction("Index");
		}
	}
}

Controllers/NoticeController.cs
using identity_2auth_mvc.Data;
using identity_2auth_mvc.Models;
using identity_2auth_mvc.Models.Klas;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace identity_2auth_mvc.Controllers
{
    public class NoticeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NoticeController(ApplicationDbContext context)
        {
            _context = context;
        }


        [HttpGet]
        public async Task<IActionResult> CourseNotice(int? id)
        {
            if (id == null)
                return NotFound();

            var noticeModel = await _context.Course
                    .Include(n => n.Notices)
                        .AsNoTracking()
                        .FirstOrDefaultAsync(m => m.CourseID == id);
            if (noticeModel == null)
                return NotFound();

            return View(noticeModel);
        }

      /*  private async Task<Course> GetNoticeHelper()
        {
            var noticeModel = new Course();
            noticeModel.Notices = await _context.Notice.ToListAsync();
            return noticeModel;
        }*/

        private async Task<IActionResult> NotePartial(int id)
        {
            var noteModel = new NoticeViewModel();
            noteModel = await _context.Notice
                    .Include(n => n.Course)
                    .AsNoTracking()
                    .FirstOrDefaultAsync(m => m.CourseId == id);
            if (noteModel == null)
                return NotFound();

            return PartialView("_TestPartial", noteModel);
        }


        public async Task<IActionResult> Index()
        {
            var courses = await _context.Course.ToListAsync();
            return View(courses);
        }

        private async Task<NoticeUploadViewModel> LoadFiles()
        {
            var viewModel = new NoticeUploadViewModel();
            viewModel.NoticesViewModel = await _context.Notice.ToListAsync();
            return viewModel;
        }

        public async Task<IActionResult> Detail(int id)
        {
            var notice = await _context.Notice.Where(x => x.Id == id).FirstOrDefaultAsync();
            if (notice == null) return NotFound();
            return View(notice);
        }

        /*	private async Task<string> GetCurrentLoggedInUserId()
			{
				AppUser user = await GetCurrentUserAsync ();
				return user?.Id;
			}*/

        // private async Task<AppUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        [HttpPost]
        public async Task<IActionResult> UploadNoticeToDB(List<IFormFile> files, string description, int courseId)
        {
            foreach (var file in files)
            {
                var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                var extension = Path.GetExtension(file.FileName);
                var noticeModel = new NoticeViewModel
                {
                    CourseId = courseId,
                    CreatedOn = DateTime.Now,
                    FileType = file.ContentType,
                    Extension = extension,
                    Name = fileName,
                    Description = description
                };

                using (var dataStream = new MemoryStream())
                {
                    await file.CopyToAsync(dataStream);
                    noticeModel.Data = dataStream.ToArray();
                }

                _context.Notice.Add(noticeModel);
                await _context.SaveChangesAsync();
            }

            TempData["Message"] = "File successfully updated to Database.";
            return RedirectToAction("Index");
        }

        // download file that attached in notice 
        public async Task<IActionResult> DownloadNoticeFromDB(int id)
        {
            var file = await _context.Notice.Where(x => x.Id == id).FirstOrDefaultAsync();
            if (file == null) return null;
            return File(file.Data, file.FileType, file.Name + file.Extension);
        }

        public async Task<IActionResult> DeleteNoticeFromDB(int id)
        {
            var file = await _context.Notice.Where(x => x.Id == id).FirstOrDefaultAsync();
            if (file == null) return null;
            _context.Notice.Remove(file);
            await _context.SaveChangesAsync();
            TempData["Message"] = $"Removed {file.Name + file.Extension} successfully from database.";
            return RedirectToAction("Index");
        }
    }
}

Views/Notice/CourseNotice.cshtml
@model Course
@{
	ViewData["Title"] = "Course Notice";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h5>@Model.CourseName | @Model.CourseID</h5>
<hr />
<form method="post" enctype="multipart/form-data">
	<input type="file" name="files" multiple required />
	<input type="text" name="Course Id" placeholder="Course ID..." />
	<input type="text" autocomplete="off" placeholder="Enter file description" name="description" required />
	<button type="submit" class="btn btn-info" asp-controller="Notice" asp-action="UploadNoticeToDB">
		Upload
	</button>
</form>
<hr />
@if (Model.Notices.Count <= 0)
{
	<caption>No records found.</caption>
}
else
{
	<caption>List of Files on File System</caption>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>File Type</th>
				<th>File</th>
				<th>Created On</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var notice in Model.Notices)
			{
				<tr>
					<td>@notice.Id</td>
					<td>
						<a class="nav-link mt-0" asp-controller="Notice" asp-action="Detail"
					asp-route-Id="@notice.Id">@notice.Name</a>
					</td>
					<td>@notice.FileType</td>
					<td>
						<a class="nav-link mt-0" asp-controller="Notice" asp-action="DownloadNoticeFromDB"
					asp-route-Id="@notice.Id">
							###
						</a>
					</td>
					<td>@notice.CreatedOn</td>
				</tr>
			}
		</tbody>
	</table>
}
<hr />

Views/Notice/Detail.cshtml
@model NoticeViewModel
@{
	ViewData["Title"] = "File Detail";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h5>Note Detail</h5>

<div class="card p-5">
	<h4>File Detail</h4>
	<div class="card-header">
		<h5>
			@Model.Description
		</h5><br />
		<p>
			File: <a class="nav-link" asp-controller="Note" asp-action="DownloadNoteFromDB"
				asp-route-Id="@Model.Id">@Model.Name</a>
		</p>
		<p>
			Created Time: @Model.CreatedOn
		</p>
	</div>
	<div class="card-body">
		<p>
			@Model.Description
		</p>
	</div>
	<div class="card-footer">
		<a type="button" class="btn btn-primary" asp-controller="Note" asp-action="DownloadNoteFromDB"
			asp-route-Id="@Model.Id">Download</a>
		<a type="button" class="btn btn-info" asp-controller="Note" asp-action="EditNote"
			asp-route-Id="@Model.Id">Edit</a>
		<a type="button" class="btn btn-danger" asp-controller="Note" asp-action="DeleteNoteFromDB"
			asp-route-Id="@Model.Id">Delete</a>
	</div>
</div>

Views/Notice/Index.cshtml
@model List<Course>
@using identity_2auth_mvc.Models.Klas 

@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<form method="post" enctype="multipart/form-data">
	<input type="file" name="files" multiple required />
	<input type="text" name="CourseId" required placeholder="Course ID..." />
	<input type="text" autocomplete="off" placeholder="Enter file description" name="description" required />
	<button type="submit" class="btn btn-info" asp-controller="Notice" asp-action="UploadNoticeToDB">
		Upload
	</button>
</form>
<hr />
*@
@*<h4>Files on File System</h4>
@if (Model.Notices.Count <= 0)
{
	<caption>No records found.</caption>
}
else
{
	<caption>List of Files on File System</caption>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>File Type</th>
				<th>File</th>
				<th>Created On</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var notice in Model.Notices)
			{
				<tr>
					<td>@notice.Id</td>
					<td>
						<a class="nav-link mt-0" asp-controller="Notice" asp-action="Detail" asp-route-Id="@notice.Id">@notice.Name</a>
					</td>
					<td>@notice.FileType</td>
					<td>
						<a class="nav-link mt-0" asp-controller="Notice" asp-action="DownloadNoticeFromDB" asp-route-Id="@notice.Id">
							###
						</a>
					</td>
					<td>@notice.CreatedOn</td>
				</tr>
			}
		</tbody>
	</table>
}
<hr />*@

<table class="table table-striped text-center">
	<thead>
		<tr>
			<th>Course ID</th>
			<th>Course Name</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var course in Model)
		{
			<tr>
				<td>@course.CourseID</td>
				<td>@course.CourseName</td>
				<td>
					<a asp-controller="Notice" asp-action="CourseNotice" asp-route-id="@course.CourseID">Detail</a>
				</td>
			</tr>
		}
	</tbody>
</table>



@section Scripts
{
	<script>
		$(document).ready(function () {
			let url = '@Url.Action("NoticePartial", "Notice")';
			$('#course_notice').on('click', function (e) {
				e.preventDefault();
				$.ajax({
					type: "POST",
					url: url
				}).done(function (result) {
					$('#notice_dashboard').html(result);
				}).fail(function (e) {
					console.log(1);
					console.log(e.responseText);
				});
			});
		});
	</script>
}

@*@if (ViewBag.Message != null)
	{
		<div class="alert alert-success alert-dismissible" style="margin-top:20px">
			@ViewBag.Message
		</div>
	}

	<form method="post" enctype="multipart/form-data">
		<input type="file" name="files" multiple required />
		<input type="text" name="CourseId" required placeholder="Course ID..."/>
		<input type="text" autocomplete="off" placeholder="Enter file description" name="description" required />
		<button type="submit" class="btn btn-info" asp-controller="Notice" asp-action="UploadNoticeToDB">
			Upload
		</button>
	</form>
	<hr />
	<h4>Files on File System</h4>
	@if (Model.NoticesViewModel.Count <= 0)
	{
		<caption>No records found.</caption>
	}
	else
	{
		<caption>List of Files on File System</caption>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>File Type</th>
					<th>File</th>
					<th>Created On</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var notice in Model.NoticesViewModel)
				{
					<tr>
						<td>@notice.Id</td>
						<td>
							<a class="nav-link mt-0" asp-controller="Notice" asp-action="Detail" asp-route-Id="@notice.Id">@notice.Name</a>
						</td>
						<td>@notice.FileType</td>
						<td>
							<a class="nav-link mt-0" asp-controller="Notice" asp-action="DownloadNoticeFromDB" asp-route-Id="@notice.Id">
								###
							</a>
						</td>
						<td>@notice.CreatedOn</td>
					</tr>
				}
			</tbody>
		</table>
	}
	<hr />*@

Views/Notice/_NoticePartial.cshtml
@model Course

@*@if (ViewBag.Message != null)
{
	<div class="alert alert-success alert-dismissible" style="margin-top:20px">
		@ViewBag.Message
	</div>
}*@

@*<form method="post" enctype="multipart/form-data">
	<input type="file" name="files" multiple required />
	<input type="text" name="CourseId" required placeholder="Course ID..." />
	<input type="text" autocomplete="off" placeholder="Enter file description" name="description" required />
	<button type="submit" class="btn btn-info" asp-controller="Notice" asp-action="UploadNoticeToDB">
		Upload
	</button>
</form>
<hr />*@
@if (Model.Notices.Count <= 0)
{
	<caption>No records found.</caption>
}
else
{
	<caption>List of Files on File System</caption>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>File Type</th>
				<th>File</th>
				<th>Created On</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var notice in Model.Notices)
			{
				<tr>
					<td>@notice.Id</td>
					<td>
						<a class="nav-link mt-0" asp-controller="Notice" asp-action="Detail" asp-route-Id="@notice.Id">@notice.Name</a>
					</td>
					<td>@notice.FileType</td>
					<td>
						<a class="nav-link mt-0" asp-controller="Notice" asp-action="DownloadNoticeFromDB" asp-route-Id="@notice.Id">
							###
						</a>
					</td>
					<td>@notice.CreatedOn</td>
				</tr>
			}
		</tbody>
	</table>
}
<hr />

}